# Scraping Books from [books toscrape website](https://books.toscrape.com/)

In [3]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [22]:
all_books_list = []

for nbr in range(1, 51) :

    url = f'https://books.toscrape.com/catalogue/page-{nbr}.html'
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    all_books = soup.find('ol', {'class' : 'row'})
    all_books = all_books.find_all('li')

    # print(len(all_books))
    for book in all_books :
        data = {}

        article = book.find('article')
        book_info = article.find('h3')
        book_link = book_info.find('a').get('href')
        data['book_link'] = f'https://books.toscrape.com/catalogue/{book_link}'
        # print(f'https://books.toscrape.com/catalogue/{book_link}')
        # -----------------------------------------
        book_page = requests.get(f'https://books.toscrape.com/catalogue/{book_link}' , book_link)
        book_page = BeautifulSoup(book_page.content, 'html.parser')
        book_page_content = book_page.find('div', {'id': 'content_inner'})
        # -----------------------------------------
        header_info = book_page_content.find('div', {'class': 'row'})
        book_img_url = header_info.find('img').get('src')
        book_title = header_info.find('h1').text.strip()
        book_price = header_info.find('p', {'class': 'price_color'}).text.strip()
        data['book_img_url'] = book_img_url
        data['book_title'] = book_title
        data['book_price'] = book_price
        # print(book_title)
        # -----------------------------------------
        product_description_div = book_page_content.find('div', {'id':'product_description'})
        product_description_paragraph = None
        if product_description_div != None :
            product_description_paragraph = product_description_div.find_next('p').text.strip()
        data['book_description'] = product_description_paragraph
        # -----------------------------------------

        table = book_page_content.find('table', {'class': 'table table-striped'})
        for row in table.find_all('tr'):
            # Get the header (th) and corresponding data (td)
            header = row.find('th').text.strip()
            value = row.find('td').text.strip()
            data[header] = value

        all_books_list.append(data)

#         for key, value in data.items():
#             print(f"{key}: {value}")

    print('nbr -> ', nbr)

nbr ->  1
nbr ->  2
nbr ->  3
nbr ->  4
nbr ->  5
nbr ->  6
nbr ->  7
nbr ->  8
nbr ->  9
nbr ->  10
nbr ->  11
nbr ->  12
nbr ->  13
nbr ->  14
nbr ->  15
nbr ->  16
nbr ->  17
nbr ->  18
nbr ->  19
nbr ->  20
nbr ->  21
nbr ->  22
nbr ->  23
nbr ->  24
nbr ->  25
nbr ->  26
nbr ->  27
nbr ->  28
nbr ->  29
nbr ->  30
nbr ->  31
nbr ->  32
nbr ->  33
nbr ->  34
nbr ->  35
nbr ->  36
nbr ->  37
nbr ->  38
nbr ->  39
nbr ->  40
nbr ->  41
nbr ->  42
nbr ->  43
nbr ->  44
nbr ->  45
nbr ->  46
nbr ->  47
nbr ->  48
nbr ->  49
nbr ->  50

In [23]:
data = pd.DataFrame(all_books_list)
data.head()

,book_link,book_img_url,book_title,book_price,book_description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
0,https://books.toscrape.com/catalogue/a-light-i...,../../media/cache/fe/72/fe72f0532301ec28892ae7...,A Light in the Attic,£51.77,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,£51.77,£51.77,£0.00,In stock (22 available),0
1,https://books.toscrape.com/catalogue/tipping-t...,../../media/cache/08/e9/08e94f3731d7d6b760dfbf...,Tipping the Velvet,£53.74,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,Books,£53.74,£53.74,£0.00,In stock (20 available),0
2,https://books.toscrape.com/catalogue/soumissio...,../../media/cache/ee/cf/eecfe998905e455df12064...,Soumission,£50.10,"Dans une France assez proche de la nôtre, un h...",6957f44c3847a760,Books,£50.10,£50.10,£0.00,In stock (20 available),0
3,https://books.toscrape.com/catalogue/sharp-obj...,../../media/cache/c0/59/c05972805aa7201171b8fc...,Sharp Objects,£47.82,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,In stock (20 available),0
4,https://books.toscrape.com/catalogue/sapiens-a...,../../media/cache/ce/5f/ce5f052c65cc963cf4422b...,Sapiens: A Brief History of Humankind,£54.23,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,£54.23,£54.23,£0.00,In stock (20 available),0

In [24]:
data.shape

(1000, 12)

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   book_link          1000 non-null   object
 1   book_img_url       1000 non-null   object
 2   book_title         1000 non-null   object
 3   book_price         1000 non-null   object
 4   book_description   998 non-null    object
 5   UPC                1000 non-null   object
 6   Product Type       1000 non-null   object
 7   Price (excl. tax)  1000 non-null   object
 8   Price (incl. tax)  1000 non-null   object
 9   Tax                1000 non-null   object
 10  Availability       1000 non-null   object
 11  Number of reviews  1000 non-null   object
dtypes: object(12)
memory usage: 93.9+ KB

In [25]:
data.to_csv('books_to_scrape.csv', index=False)